apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: boilerplate-spa
      tier: api
  replicas: 3
  template:
    metadata:
      labels:
        app: boilerplate-spa
        tier: api
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: boilerplate-spa-api
          image: ataquino/boilerplate-spa-api
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: PORT
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: TOKEN_SECRET